# Generated by Django 4.2.5 on 2023-12-04 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('audio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('audio_name', models.CharField(max_length=200)),
                ('audio_link', models.CharField(max_length=200)),
            ],
        ),
    ]
