# Generated by Django 4.2.5 on 2023-12-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0004_audio_audio_description_audio_audio_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_type',
            field=models.CharField(default='undefined', max_length=20),
        ),
    ]
