# Generated by Django 4.2.5 on 2023-12-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0007_audiolist_delete_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiolist',
            name='audio',
            field=models.ManyToManyField(to='aus.audio'),
        ),
    ]
