# Generated by Django 4.2.5 on 2023-12-18 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0009_remove_audiolist_audio_audiolistdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audioListDetail',
        ),
    ]
