# Generated by Django 4.2.5 on 2023-12-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0010_delete_audiolistdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='audioInList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
                ('audio_name', models.CharField(max_length=200)),
            ],
        ),
    ]
