# Generated by Django 4.2.5 on 2023-12-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0011_audioinlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='audioInList',
            new_name='listContent',
        ),
    ]
