# Generated by Django 4.2.5 on 2024-01-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0015_alter_listcontent_content_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listcontent',
            name='content_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
