# Generated by Django 4.2.5 on 2023-12-18 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0008_audiolist_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiolist',
            name='audio',
        ),
        migrations.CreateModel(
            name='audioListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aus.audio')),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aus.audiolist')),
            ],
        ),
    ]
