# Generated by Django 4.2.5 on 2024-01-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0012_rename_audioinlist_listcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='activeHeartAudio',
            fields=[
                ('heart_audio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('heart_audio_name', models.CharField(max_length=200)),
                ('heart_audio_type', models.CharField(default='undefined', max_length=20)),
                ('heart_audio_description', models.CharField(default='', max_length=500)),
                ('heart_audio_level', models.CharField(default='All levels', max_length=20)),
                ('heart_audio_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='activeLungAudio',
            fields=[
                ('lung_audio_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lung_audio_name', models.CharField(max_length=200)),
                ('lung_audio_type', models.CharField(default='undefined', max_length=20)),
                ('lung_audio_description', models.CharField(default='', max_length=500)),
                ('lung_audio_level', models.CharField(default='All levels', max_length=20)),
                ('lung_audio_link', models.CharField(max_length=200)),
            ],
        ),
    ]
