# Generated by Django 4.2.5 on 2024-01-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0013_activeheartaudio_activelungaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listcontent',
            name='id',
        ),
        migrations.AddField(
            model_name='listcontent',
            name='audio_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listcontent',
            name='content_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='listcontent',
            name='list_id',
            field=models.IntegerField(default=0),
        ),
    ]
