# Generated by Django 4.2.5 on 2024-01-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0017_alter_audiolist_list_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeheartaudio',
            name='heart_audio_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activelungaudio',
            name='lung_audio_list',
            field=models.IntegerField(default=0),
        ),
    ]
