# Generated by Django 4.2.5 on 2024-01-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aus', '0018_activeheartaudio_heart_audio_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeheartaudio',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='activeheartaudio',
            name='heart_audio_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activelungaudio',
            name='lung_audio_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
