# Generated by Django 5.0 on 2024-01-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aus", "0019_activeheartaudio_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeheartaudio",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="activelungaudio",
            name="lung_audio_id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
